version: 0.2
phases:
  install:
    commands:
      - echo Build started on `date`
      - pip install -r requirements.txt
      - pip install -r requirements.txt -t hello_world/build/
      - cp hello_world/*.py hello_world/build/
  build:
    commands:
      - python -m pytest tests/ -v
  post_build:
    commands:
      - sam package --template-file template.yaml --output-template-file packaged.yaml --s3-bucket aws-sam-lambda
    