version: 0.2
phases:
  install:
    commands:
      - echo Build started on `date`
      - pip install -r requirements.txt
      - pip install -r requirements.txt -t hello_world/build/
      - cp hello_world/*.py hello_world/build/
      - aws cloudformation package --template-file template.yaml --kms-key-id 119f81b2-b2d3-450e-9fa8-865ed6a8e92d --s3-bucket aws-sam-lambda 
                                   --output-template-file outputSamTemplate.yaml
  build:
    commands:
      - python -m pytest tests/ -v
artifacts:
  type: zip
  files:
    - template.yaml
    - outputSamTemplate.yaml
